server:
  port: 8010

spring:
  application:
    name: ming-shop-service-member

###服务注册到eureka地址
eureka:
  client:
    service-url:
      # 开启安全验证时的注册地址
       defaultZone: http://ming:ming@106.12.217.33:8761/eureka
#    注册服务和检索服务默认开启为true
  instance:
    # 以服务IP访问
    prefer-ip-address: true
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2